import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Full WACC Model (Textbook Example)", layout="centered")

st.title("📘 Weighted Average Cost of Capital — Multi-Source Example")

st.markdown("""
This version replicates the **textbook WACC example** including:
- Ordinary shares (equity) using the **Gordon Growth Model**  
- Preference shares  
- Redeemable bonds (Hawawini–Vora yield)  
- Irredeemable bonds  
- Bank loans (after tax)

Each cost is adjusted for tax as applicable, and weighted by market value.
""")

# ───────────────────────────────────────────────
# Default Data from the image example
# ───────────────────────────────────────────────
st.header("Step 1️⃣  —  Input Data")

tax_rate = st.number_input("Corporation tax rate (%)", value=30.0, step=0.1)

data = [
    {"Source": "Ordinary shares", "Market Value (£m)": 417, "Cost (%)": 10.8, "After-Tax?": False},
    {"Source": "Preference shares", "Market Value (£m)": 89, "Cost (%)": 9.0, "After-Tax?": False},
    {"Source": "Redeemable bonds", "Market Value (£m)": 96, "Cost (%)": 5.8, "After-Tax?": True},
    {"Source": "Irredeemable bonds", "Market Value (£m)": 108, "Cost (%)": 9.0, "After-Tax?": True},
    {"Source": "Bank loans", "Market Value (£m)": 7, "Cost (%)": 7.0, "After-Tax?": True},
]
df = pd.DataFrame(data)

st.dataframe(df, use_container_width=True)

# ───────────────────────────────────────────────
# Apply tax adjustment
# ───────────────────────────────────────────────
df["Effective Cost (%)"] = np.where(
    df["After-Tax?"],
    df["Cost (%)"] * (1 - tax_rate / 100),
    df["Cost (%)"]
)

df["Total Value"] = df["Market Value (£m)"]
total_capital = df["Total Value"].sum()
df["Weight"] = df["Total Value"] / total_capital
df["Weighted Cost (%)"] = df["Weight"] * df["Effective Cost (%)"]

# ───────────────────────────────────────────────
# Display results
# ───────────────────────────────────────────────
st.header("Step 2️⃣  —  Weighted Average Calculation")
st.write(f"**Total Market Value (V)** = £{total_capital:,.0f} million")

st.dataframe(
    df[["Source", "Market Value (£m)", "Effective Cost (%)", "Weight", "Weighted Cost (%)"]],
    use_container_width=True
)

wacc = df["Weighted Cost (%)"].sum()

st.success(f"✅ **Weighted Average Cost of Capital (WACC) = {wacc:.2f}%**")

# ───────────────────────────────────────────────
# Detailed workings
# ───────────────────────────────────────────────
with st.expander("Show formula and interpretation"):
    st.latex(r"""
    WACC = \sum_i w_i K_i (1 - T_i)
    """)
    st.markdown(f"""
    **Effective after-tax rates (as in example):**
    - Redeemable bonds: 5.8 × (1−0.30) = 4.1 %
    - Irredeemable bonds: 9 × (1−0.30) = 5.8 %
    - Bank loans: 7 × (1−0.30) = 4.9 %

    Weighted together:
    \\[
    WACC = {wacc:.2f}\%
    \\]
    """)

st.caption("Generated by AI (ChatGPT) under supervision of A. McBride — textbook replication, WACC multi-source edition.")
